### ISSUE TITLE
Simple Web App

### ISSUE THREAD

**Issue by RyanMurphyWWT** [mmumshad/simple-webapp-flask#1]
Section 2 shows the following;

Copy app.py or download it from source repository
Configure database credentials and parameters

Can you explain where to put the app.py file and how to configure database credential and parameters?

**Comment by lotosotol** [comment]
BTW, this seems to not be valid for the https://kodekloud.com/courses/296044/lectures/4554709 course anymore (minute 5 of the video - different code).

**Comment by CMapara** [comment]
You have to manually add the configs
